version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=neurosift_jobs
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
